### ISSUE TITLE
Tried to interpose open system call but it is not getting overriden in excel

### ISSUE THREAD

**Issue by PremsagarT** [scen/osxinj#1]
Using this project, I hooked open system call and injected in excel. But new open is not getting called. The hooking for read and write system calls are working fine. Even hooking for open system call on TextEdit is working fine and messages are logged in system.log. I verified using dtruss that open system call is being called by Excel whenever new workbook is created. Any kind help is appreciated or any thoughts to try.

**Comment by PremsagarT** [comment]
used __open

**Comment by scen** [comment]
glad it worked out.

**Comment by PremsagarT** [comment]
Thanks.. I assume they both are alias. But I am still struggling to find out difference of open and __open. Even read is __read and same for write.

**Comment by scen** [comment]
my best guess is that they call some other function such as `fopen()` or their own custom wrapper that calls this lower-level `__open()` function.
