### ISSUE TITLE
mac os sierra crashes failed to inject: module:0x0 bootstrapfn:0x0

### ISSUE THREAD

**Issue by philosofonusus** [scen/osxinj#8]
failed to inject: module:0x0 bootstrapfn:0x0

**Comment by iraizo** [comment]
You need the bootstrap.dylib at the same directory too

**Comment by philosofonusus** [comment]
mach_inject: found threadEntry image at: 0xde000 with size: 9888
mach_inject failing.. (os/kern) invalid address

**Comment by philosofonusus** [comment]
help me
